AllCops:
  DisplayCopNames: true
  Exclude:
    - '*.gemspec'
    - spec/**/*
    - vendor/**/*

Metrics/AbcSize:
  Severity: error

Metrics/ClassLength:
  Max: 250
  Severity: error

Metrics/CyclomaticComplexity:
  Severity: error

Metrics/LineLength:
  Max: 100
  Severity: error

Metrics/MethodLength:
  Max: 10
  Severity: error

Metrics/ModuleLength:
  Max: 150
  Severity: error

Metrics/ParameterLists:
  Max: 4
  Severity: warning

# Keep for now, easier with superclass definitions
ClassAndModuleChildren:
  Enabled: false

# The ones we use must exist for the entire class hierarchy.
ClassVars:
  Enabled: false

# Well, well, well
Documentation:
  Enabled: false

# Keep single line bodys for if and unless
IfUnlessModifier:
  Enabled: false

# We thinks that's fine for specs
Layout/EmptyLinesAroundBlockBody:
  Enabled: false

# We thinks that's fine
Layout/EmptyLinesAroundClassBody:
  Enabled: false

# We thinks that's fine
Layout/EmptyLinesAroundModuleBody:
  Enabled: false

# We think that's the developers choice
Style/GuardClause:
  Enabled: false
