AllCops:
  DisplayCopNames: true
  Exclude:
    - spec/**/*

Metrics/AbcSize:
  Max: 17
  Severity: error

Metrics/ClassLength:
  Max: 200
  Severity: error

Metrics/CyclomaticComplexity:
  Max: 6
  Severity: error

Metrics/LineLength:
  Max: 100
  Severity: error

Metrics/MethodLength:
  Max: 10
  Severity: error

Metrics/ModuleLength:
  Max: 200
  Severity: error

Metrics/ParameterLists:
  Max: 4
  Severity: warning

# Keep for now, easier with superclass definitions
ClassAndModuleChildren:
  Enabled: false

# The ones we use must exist for the entire class hierarchy.
ClassVars:
  Enabled: false

# Well, well, well
Documentation:
  Enabled: false

# Missing UTF-8 encoding statements should always be created.
Encoding:
  Severity: error

# Keep single line bodys for if and unless
IfUnlessModifier:
  Enabled: false

# That's no huge stopper
Layout/EmptyLines:
  Enabled: false

# We thinks that's fine for specs
Layout/EmptyLinesAroundBlockBody:
  Enabled: false

# We thinks that's fine
Layout/EmptyLinesAroundClassBody:
  Enabled: false

# We thinks that's fine
Layout/EmptyLinesAroundModuleBody:
  Enabled: false

# We thinks that's fine
Layout/MultilineOperationIndentation:
  Enabled: false

# But probably more readable...
Lint/AmbiguousBlockAssociation:
  Enabled: false

# We thinks that's fine
Style/EmptyMethod:
  Enabled: false

# just false positives for 0.51.0
Style/MixinUsage:
  Enabled: false

# Not sure if this is really an established community standard
Style/PercentLiteralDelimiters:
  Enabled: false

# We thinks that's fine
Style/RegexpLiteral:
  Enabled: false

# We thinks that's fine
Style/SymbolArray:
  Enabled: false

# We think that's the developers choice
Style/SymbolProc:
  Enabled: false

# We thinks that's fine
Style/SingleLineBlockParams:
  Enabled: false

# We think that's the developers choice
Style/GuardClause:
  Enabled: false
